# Generated by Django 4.2 on 2023-05-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
