# Generated by Django 4.2 on 2023-05-06 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                default=1,
                max_length=20,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
            preserve_default=False,
        ),
    ]
